### ISSUE TITLE
Invite people by link feature - IPBL

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-api#23]
⚠️ Read carefully the business rules of project
 
## Requirement
- [ ] Implement Redis Service to cache link

## Tasks
- [ ] **IPBL** Repository
- [ ] **IPBL** service
- [ ] **IPBL** Controller
- [ ] **IPBL** Swagger API
- [ ] **IPBL** Unit Test
