### ISSUE TITLE
Search Staff Feature

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-api#29]
## Requirement

- [ ] Full-text search --> Elastic Search  or Algolia Search

## Supporter
@phanduc0908 

## Tasks

- [ ] Search Staff Repository
- [ ] Search Staff Service
- [ ] Search Staff Controller
- [ ] Search Staff Swagger API
- [ ] Search Staff Unit Test
