### ISSUE TITLE
Choose & implement full-text search engine

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-api#30]
## Tasks

- [ ] Choose between Elastic search or [Algolia search](https://www.algolia.com/)(Good --> Free for Github student)
- [ ] Full-text Search Service
- [ ] Full-text Search Repository???
- [ ] Full-text Search Controller
- [ ] Full-text Search Swagger API
- [ ] Full-text Search Unit Test
